name: Push

on:
  push:
jobs:
  # 1. Test + CodeCoverage
  test-codecov:
    uses: fptiangco/githubactions-test/.github/workflows/wf_test_codecov.yml@main
    secrets:
       codecovtoken: ${{ secrets.CODECOV_TOKEN }}
